services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
